### ISSUE TITLE
Referring to the GPL3.0-licensed OSS

### ISSUE THREAD

**Issue by yuto0222** [Shunichi09/PythonLinearNonlinearControl#7]
Hello.
Thanks for the great work.

You are using the following as a reference, but [studywolf's control](https://github.com/studywolf/control) is GPL-licensed, is that ok?(It looks like an algorithmic copy, not a code copy.)

```
  """ iterative Liner Quadratique Regulator
    Ref:
        Tassa, Y., Erez, T., & Todorov, E. (2012). . In 2012 IEEE/RSJ International Conference on
        Intelligent Robots and Systems (pp. 4906-4913). and Study Wolf,
        https://github.com/studywolf/control
    """
```
https://github.com/Shunichi09/PythonLinearNonlinearControl/blob/master/PythonLinearNonlinearControl/controllers/ilqr.py#L17

This project was personally developed, so it doesn't sound like you did the "[clean room design](https://en.wikipedia.org/wiki/Clean_room_design)"...

**Comment by Shunichi09** [comment]
Thank you for pointing out. Did you mean I have to use the GPL-licensed, not MIT-licensed ??

**Comment by yuto0222** [comment]
Codes of ilqt(and ddp?) written with reference to the applicable GPL license must be licensed under the GPL, but you are not required to GPL all your software.

You need to specify the licenses individually as follows
https://github.com/RainerKuemmerle/g2o
```
License

g2o is licensed under the BSD License. However, some libraries are available under different license terms. See below.

The following parts are licensed under LGPL3+:

    csparse_extension

The following parts are licensed under GPL3+:

    g2o_viewer
    g2o_incremental
    slam2d_g2o (example for 2D SLAM with a QGLviewer GUI)

```

**Comment by yuto0222** [comment]
If you make a program using GPL-licensed code, you have to publish all of that code, and companies don't like to use the GPL license.
Since your oss has a star-studded repository, this could cause a lot of people to unknowingly slip the GPL license into their products, which would cause a lot of trouble for many people.

**Comment by Shunichi09** [comment]
I'm sorry for the late reply. I really appreciate your pointing out and kindness.
I've fixed my license status!! Please check it.
